name: CD

on:
  workflow_dispatch:
    inputs:
      update-tag:
        description: "input yes means bump up tag version, and no means update the tag to top"
        required: true
        default: "no"
jobs:
  cd:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Validate CD branch
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/release' && github.ref != 'refs/heads/main' }}
        run: |
          echo It's not allowed to run CD on other branch except release.
          exit 1
      
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: fetch latest tag
        uses: actions-ecosystem/action-get-latest-tag@b7c32daec3395a9616f88548363a42652b22d435 # v1.6.0
        id: get-latest-tag
      
      - name: update tag
        uses: richardsimko/update-tag@24fe62c216198eb57283429200e63a06f62afe5b # v3.0.0
        if: ${{ github.event.inputs.update-tag == 'no' }}
        with:
          tag_name: ${{ steps.get-latest-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        if: ${{ github.event.inputs.update-tag != 'no' }}
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8 # 1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: ${{ steps.get-latest-tag.outputs.tag }}
          RELEASE_BRANCHES: "main"
